name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Отримання коду репозиторію
        uses: actions/checkout@v4

      - name: Налаштування SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 38.242.214.198 >> ~/.ssh/known_hosts

      - name: Розгортання та перезапуск служб
        run: |
          ssh root@38.242.214.198 << 'EOF'
            export NVM_DIR=~/.nvm;
            source ~/.nvm/nvm.sh;
            export PATH=/root/.nvm/versions/node/v20.18.1/bin:$PATH;
            
            echo "🚀 Починаємо деплой на сервер..."
            cd /var/www/shina-mix-landing/back

            echo "📥 Оновлюємо репозиторій..."
            git fetch --all
            git reset --hard origin/main
            git clean -X --exclude=".env"
            git pull origin main
            
            echo "📦 Встановлюємо залежності..."
            npm install
            
            echo "⚙️ Будуємо Strapi..."
            npm run build

            echo "🚀 Перезапускаємо Strapi..."
            pm2 restart strapi
            
            echo "✅ Деплой завершено!"
          EOF